# Generated by Django 4.0.4 on 2022-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('nuapproved', 'Nnapproced'), ('approved', 'Approced'), ('bened', 'Bened')], default='nuapproved', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
