# Generated by Django 4.0.4 on 2022-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsciption',
            name='status',
            field=models.CharField(choices=[('unapproved', 'Unapproced'), ('approved', 'Approced'), ('bened', 'Bened')], default='unapproved', max_length=15),
        ),
    ]
