# Generated by Django 4.0.4 on 2022-05-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_subsciption_food_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsciption',
            name='food_set',
        ),
    ]
