# Generated by Django 4.0.4 on 2022-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='promotion',
            new_name='promotion_end_at',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='special_pricec',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
