# Generated by Django 4.0.4 on 2022-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0002_rename_promotion_food_promotion_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='special_pricec',
            field=models.IntegerField(null=True),
        ),
    ]
