# Generated by Django 4.0.4 on 2022-05-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0003_alter_food_special_pricec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='special_pricec',
            new_name='special_price',
        ),
    ]
